big_carousel_slides:
  default: >-
    [{"link": "https://google.com", "headline":"WOah", "text":"Hello there", "button_text": "button", "image_url":"", "slide_type":"slide"},
    { "link": "https://google.com",  "headline":"Big headline", "text":"Hello there", "button_text": "button", "image_url":"", "slide_type":"slide"},
    { "link": "discobot",  "headline":"Big headline", "text":"Hello there", "button_text": "button", "image_url":"", "slide_type":"user"}]
  json_schema: '{ "type": "array", "format": "table", "uniqueItems": true, "items": { "type": "object", "properties": { "link": { "type": "string", "minLength": 1 }, "headline": {"type": "string"}, "text": { "type": "string", "minLength": 1 }, "button_text": {"type": "string"}, "image_url": { "type": "string" }, "slide_type": {"type": "string"} }, "additionalProperties": false } }'

big_carousel_min_height:
  type: string
  default: 300px

big_carousel_autoplay:
  type: bool
  default: false

big_carousel_speed:
  type: integer
  default: 300

plugin_outlet:
  type: enum
  default: below-site-header
  choices:
    - below-site-header
    - above-main-container
